server:
  port: 8091
  tomcat:
    threads:
     max: 5 #tomcat的最⼤并发值修改为10,
spring:
  cloud:
   nacos:
    discovery:
     server-addr: localhost:8848
   sentinel:
     web-context-unify: false
     transport:
       port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
       dashboard: localhost:8080 # 指定控制台服务的地址
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///shop-order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yuxun
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
product-service: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule